version: 0.2

env:
  variables:
    AWS_REGION: "eu-west-1"
    LAMBDA_FUNCTION_NAME: "blog-lambda-posts"  # <-- your real Lambda name

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Backend install phase (Lambda), CWD:$(pwd)"
      - cd backend
      - if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - cd ..

  pre_build:
    commands:
      - echo "Running backend tests (if any)..."
      - cd backend
      - npm test || echo "No tests configured, skipping"
      - cd ..

  build:
    commands:
      - echo "Packaging backend for Lambda..."
      - cd backend
      - zip -r ../backend-lambda.zip . -x "node_modules/aws-sdk/*"
      - cd ..

  post_build:
    commands:
      - echo "Updating Lambda function. Name:'$LAMBDA_FUNCTION_NAME' Region:'$AWS_REGION'"
      - aws lambda update-function-code --function-name "$LAMBDA_FUNCTION_NAME" --zip-file fileb://backend-lambda.zip --region "$AWS_REGION"
      - echo "Lambda code update complete."


artifacts:
  files:
    - backend-lambda.zip
